from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / "files"
WINDOW_ICON_PATH = FILES_DIR / "icon.png"

# Colors
PRIMARY_COLOR = "#1e81b0"
DARKER_PRIMARY_COLOR = "#16658a"
DARKEST_PRIMARY_COLOR = "#115270"

# Sizing
BIG_FONT_SIZE = 25
MEDIUM_FONT_SIZE = 20
SMALL_FONT_SIZE = 15
TEXT_MARGIN = 15
MINIMUM_WIDHT = 150

# Range for x and y
XY_RANGE = (-10, 10)

# Backpropagation
LEARNING_RATE_BACKPROP = 0.001
TOLERANCE_BACKPROP = 1e-6
MAX_ITERATIONS_BACKPROP = 10000
